### ISSUE TITLE
Allow connection string variable name to be set in the pyproject

### ISSUE THREAD

**Issue by kelvins** [kelvins/nomade#7]
Allow connection string variable name to be set in the `pyproject.toml`, for example:
```toml
[tool.nomade]
connection-string-variable = "APP_CONNECTION_STRING"
```

Then, it should load the env var as:

```python
import os
os.getenv('APP_CONNECTION_STRING')
```
